package repopulse.server.dto.analytics.pullrequest;

public enum PullRequestInsightType
{
    BACKLOG_GROWING,
    MEDIAN_MERGE_TIME_HIGH,
    MEDIAN_MERGE_TIME_INCREASED,
    MERGE_RATE_LOW,
    MERGE_RATE_DROPPED,
    MERGE_THROUGHPUT_DROPPED,
    STALE_OPEN_PULL_REQUEST_RATE_HIGH,
    OVERSIZED_PULL_REQUEST_SHARE_HIGH,
    OVERSIZED_MERGE_TIME_HIGHER,
    OVERSIZED_MERGE_RATE_LOWER,
    SIZE_ASSOCIATED_WITH_LONGER_MERGE_TIME,
    STALE_OVERSIZED_OPEN_PULL_REQUESTS
}