CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_user_id BIGINT NOT NULL UNIQUE,
    github_login VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE repositories (
    repository_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id BIGINT NOT NULL UNIQUE,
    owner VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    html_url VARCHAR(255) NOT NULL,
    default_branch VARCHAR(255) NOT NULL,
    last_synced_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    orphaned_at TIMESTAMPTZ
);

CREATE TABLE pull_requests (
    pull_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id BIGINT NOT NULL UNIQUE,
    repository_id BIGINT NOT NULL REFERENCES repositories(repository_id) ON DELETE CASCADE,

    number INTEGER NOT NULL,
    state VARCHAR(20) NOT NULL,
    title VARCHAR(500) NOT NULL,
    html_url TEXT NOT NULL,
    author_login VARCHAR(100) NOT NULL,
    draft BOOLEAN NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,
    closed_at TIMESTAMPTZ,
    merged_at TIMESTAMPTZ,

    UNIQUE (repository_id, number)
);

CREATE TABLE user_repositories (
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    repository_id BIGINT NOT NULL REFERENCES repositories(repository_id) ON DELETE CASCADE,
    tracked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (user_id, repository_id)
);

CREATE INDEX idx_user_repositories_repository_id
ON user_repositories(repository_id);